/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class', '[data-theme="dark"]'],
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Colors use rgb() wrapper + CSS variable channels so opacity modifiers (bg-primary/20 etc.) work
        primary: {
          DEFAULT: 'rgb(var(--primary) / <alpha-value>)',
          foreground: 'rgb(var(--primary-foreground) / <alpha-value>)',
          50:  '#edf7fa',
          100: '#d5edf2',
          200: '#aedce6',
          300: '#7ac4d5',
          400: '#3fa4bd',
          500: '#096882',
          600: '#07586f',
          700: '#06475a',
          800: '#053847',
          900: '#042b37',
        },
        accent: {
          DEFAULT: 'rgb(var(--accent) / <alpha-value>)',
          foreground: 'rgb(var(--accent-foreground) / <alpha-value>)',
          50:  '#e6fbfb',
          100: '#c2f7f5',
          200: '#8df0ec',
          300: '#4de4de',
          400: '#1adcd5',
          500: '#00d9d0',
          600: '#00b5ad',
          700: '#008f89',
          800: '#006e6a',
          900: '#005552',
        },
        green: {
          DEFAULT: 'rgb(var(--green) / <alpha-value>)',
          foreground: 'rgb(var(--green-foreground) / <alpha-value>)',
          50:  '#edf7f0',
          100: '#d4edd9',
          200: '#aedebb',
          300: '#7ec995',
          400: '#52b070',
          500: '#309952',
          600: '#268143',
          700: '#206837',
          800: '#1c532d',
          900: '#174426',
        },
        dark: {
          DEFAULT: 'rgb(var(--dark) / <alpha-value>)',
          foreground: 'rgb(var(--dark-foreground) / <alpha-value>)',
          50:  '#edf2f7',
          100: '#d4dfec',
          200: '#adc3dc',
          300: '#7fa1c7',
          400: '#4e7caf',
          500: '#071b3a',
          600: '#06162f',
          700: '#051226',
          800: '#040d1c',
          900: '#030913',
        },
        paper: 'rgb(var(--background) / <alpha-value>)',
        paperDim: 'rgb(var(--card) / <alpha-value>)',
        ink: 'rgb(var(--foreground) / <alpha-value>)',
        inkSoft: 'rgb(var(--muted-foreground) / <alpha-value>)',
        line: 'rgb(var(--border) / <alpha-value>)',
        secondary: {
          DEFAULT: 'rgb(var(--secondary) / <alpha-value>)',
          foreground: 'rgb(var(--secondary-foreground) / <alpha-value>)',
        },
        background: 'rgb(var(--background) / <alpha-value>)',
        foreground: 'rgb(var(--foreground) / <alpha-value>)',
        card: {
          DEFAULT: 'rgb(var(--card) / <alpha-value>)',
          foreground: 'rgb(var(--card-foreground) / <alpha-value>)',
        },
        muted: {
          DEFAULT: 'rgb(var(--muted) / <alpha-value>)',
          foreground: 'rgb(var(--muted-foreground) / <alpha-value>)',
        },
        border: 'rgb(var(--border) / <alpha-value>)',
        input: 'rgb(var(--input) / <alpha-value>)',
        ring: 'rgb(var(--ring) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        xl: '1rem',
        '2xl': '1.25rem',
        '3xl': '1.75rem',
      },
      boxShadow: {
        soft: 'var(--shadow-soft)',
        card: 'var(--shadow-card)',
        hover: 'var(--shadow-hover)',
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.6s ease-out forwards',
        'pulse-soft': 'pulse-soft 3s ease-in-out infinite',
        float: 'float 4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
